import { AnimeData } from './types';

export const ANIME_CATALOG: Record<string, AnimeData> = {
  'kamui': {
    id: 'kamui',
    title: 'Kamui',
    kanji: '神威',
    badge: 'KAMUI ORIGINAL',
    badgeType: 'original',
    genre: 'Dark fantasy',
    genres: ['Dark Fantasy', 'Supernatural', 'Action', 'Mythology'],
    year: '2026',
    rating: '16+',
    match: '98% Match',
    seasonsCount: '1 Season (24 Episodes)',
    trailerVideo: '/kamui-animation.mp4',
    fullVideo: '/kamui-animation.mp4',
    hook: 'When the northern bells chime in the dead of winter, the banished wolf-god must answer.',
    synopsis: 'A shrine girl who hears what the bells are saying, and the exiled wolf-god bound to her by a debt neither of them chose. Together they walk north into the forbidden frost to find out why winter has stopped ending.',
    cast: 'Kenjiro Tsuda, Megumi Ogata, Mamoru Miyano, Saori Hayami',
    mood: 'Mythological, Dark Fantasy, Gripping, Visual Masterpiece',
    studio: 'Kamui Originals × Studio MAPPA',
    director: 'Sunao Katabuchi',
    audio: 'Japanese [Original], English (Dub), French, German',
    subtitles: 'English [CC], Japanese, Spanish, German, French',
    maturityDesc: 'Violence, dark supernatural themes, intense action scenes.',
    episodes: [
      { num: 1, title: 'The Bell of Frozen Ash', duration: '24m', desc: 'A frost settles over the mountain shrine, and a voice in the chime awakens an ancient pact between maiden and exiled wolf.' },
      { num: 2, title: 'Howling at the Eclipse', duration: '23m', desc: 'Tracked by imperial hunters, the maiden and the wolf enter the forbidden forest of Oku under a blood moon.' },
      { num: 3, title: 'Crimson Snowfall', duration: '25m', desc: 'An encounter with a shrine sentinel reveals the dark truth behind the endless blizzard consuming the northern realm.' },
      { num: 4, title: 'The Blade that Remembers', duration: '24m', desc: 'In the ruins of the northern capital, a spirit forge reignites to temper a blade capable of cutting divinity.' }
    ],
    relatedIds: ['long-thaw', 'iron-tide', 'nine-crows-inn']
  },
  'ashfall-district': {
    id: 'ashfall-district',
    title: 'Ashfall District',
    kanji: '灰落街',
    badge: 'TRENDING #1',
    badgeType: 'trending',
    genre: 'Sci-fi',
    genres: ['Sci-Fi', 'Cyberpunk', 'Mystery', 'Action'],
    year: '2026',
    rating: '13+',
    match: '96% Match',
    seasonsCount: '1 Season (22 Episodes)',
    trailerVideo: '/kamui-hero.mp4',
    fullVideo: '/kamui-hero.mp4',
    hook: 'Deep inside the volcanic crater, neon lights flicker as the geothermal plasma grid destabilizes.',
    synopsis: 'A city built inside the crater of an extinct volcano runs on power no one can explain. When the grid starts failing block by block, two rival engineers have to trust each other to find out what is hidden underneath it.',
    cast: 'Kaito Ishikawa, Sora Amamiya, Takahiro Sakurai, Yoko Hikasa',
    mood: 'Neon Noir, Cyberpunk, Mind-Bending, High Octane',
    studio: 'Studio Trigger × Kamui',
    director: 'Hiroyuki Imaishi',
    audio: 'Japanese [Original], English (Dub), Portuguese, Italian',
    subtitles: 'English [CC], Japanese, Spanish, Italian, German',
    maturityDesc: 'Sci-fi violence, peril, language.',
    episodes: [
      { num: 1, title: 'Blackout Protocol', duration: '23m', desc: 'Sector 7 loses auxiliary power as a phantom signal spreads through the plasma reactor conduits.' },
      { num: 2, title: 'Sub-Level Zero', duration: '24m', desc: 'Descending into the magma shaft, the engineers discover ancient subterranean machinery that shouldn\'t exist.' },
      { num: 3, title: 'Neon Ash', duration: '22m', desc: 'Corporate enforcers move in to silence the maintenance crew before the grid malfunction leaks to the populace.' },
      { num: 4, title: 'Overclocked Pulse', duration: '25m', desc: 'A desperate gamble to jumpstart the secondary geothermal turbine before the core implodes.' }
    ],
    relatedIds: ['static-requiem', 'iron-tide', 'kamui']
  },
  'paper-moon-society': {
    id: 'paper-moon-society',
    title: 'Paper Moon Society',
    kanji: '紙月会',
    badge: 'STAFF PICK',
    genre: 'Slice of life',
    genres: ['Slice of Life', 'Comedy', 'Drama', 'Cozy'],
    year: '2026',
    rating: 'All Ages',
    match: '95% Match',
    seasonsCount: '1 Season (12 Episodes)',
    trailerVideo: '/kamui-animation.mp4',
    fullVideo: '/kamui-animation.mp4',
    hook: 'Four strangers, an antique bookstore after midnight, and stories that heal quiet wounds.',
    synopsis: 'Four strangers rent the same failing bookshop after hours, one night a week, for reasons none of them explain to each other. A quiet, funny season about the kind of friendship you don\'t plan for.',
    cast: 'Nao Toyama, Yoshitsugu Matsuoka, Rie Takahashi, Hiroshi Kamiya',
    mood: 'Heartwarming, Nostalgic, Quirky, Soothing',
    studio: 'Kyoto Animation × Kamui',
    director: 'Naoko Yamada',
    audio: 'Japanese [Original], English (Dub), German',
    subtitles: 'English [CC], Japanese, French, Spanish',
    maturityDesc: 'Mild emotional themes, suitable for all audiences.',
    episodes: [
      { num: 1, title: 'Friday at Midnight', duration: '22m', desc: 'The bell rings above the door at 12:05 AM as four unlikely visitors claim different corners of the shop.' },
      { num: 2, title: 'The Book of Lost Marginalia', duration: '23m', desc: 'Notes left in the margins of a 1920s poetry book spark an unexpected late-night investigation.' },
      { num: 3, title: 'Tea and Second Chances', duration: '21m', desc: 'A rainy night brings homemade matcha treats and unspoken confessions between the bookshelves.' },
      { num: 4, title: 'The Bookmark with No Name', duration: '24m', desc: 'A hidden photograph between the pages of an antique dictionary connects two patrons\' pasts.' }
    ],
    relatedIds: ['glasshouse', 'hollow-meridian', 'kamui']
  },
  'iron-tide': {
    id: 'iron-tide',
    title: 'Iron Tide',
    kanji: '鉄潮',
    badge: 'POPULAR',
    genre: 'Mecha',
    genres: ['Mecha', 'Sci-Fi', 'Military Action', 'Adventure'],
    year: '2026',
    rating: '16+',
    match: '97% Match',
    seasonsCount: '1 Season (26 Episodes)',
    trailerVideo: '/kamui-hero.mp4',
    fullVideo: '/kamui-hero.mp4',
    hook: 'The rising oceans took the continents. Only titan-class pilot frames can reclaim the abyss.',
    synopsis: 'The ocean took back three coastal nations in a single decade. What\'s left of their navies is now a scrapyard of pilot-grade frames, and a teenage salvager just found the one still worth flying.',
    cast: 'Jun Fukuyama, Marina Inoue, Tomokazu Sugita, Kana Hanazawa',
    mood: 'Epic, Heavy Machinery, Strategic, Adrenaline',
    studio: 'Sunrise × Kamui',
    director: 'Goro Taniguchi',
    audio: 'Japanese [Original], English (Dub), Spanish',
    subtitles: 'English [CC], Japanese, Korean, Italian',
    maturityDesc: 'Mecha combat, mild blood, explosions.',
    episodes: [
      { num: 1, title: 'Dredged from the Deep', duration: '26m', desc: 'A routine salvage dive in the underwater trench unearths an intact Mark-IV combat rig.' },
      { num: 2, title: 'Pressure Breach', duration: '24m', desc: 'Pirate cruisers ambush the salvage barge during heavy sea storms to seize the relic.' },
      { num: 3, title: 'Echo of the Reactor', duration: '25m', desc: 'The neural sync interface accepts an unregistered teenage pilot for the first time in thirty years.' },
      { num: 4, title: 'Trench Warfare', duration: '24m', desc: 'Deploying into the pitch-black ocean depths against rogue automated defense drones.' }
    ],
    relatedIds: ['ashfall-district', 'kamui', 'hollow-meridian']
  },
  'nine-crows-inn': {
    id: 'nine-crows-inn',
    title: 'Nine Crows Inn',
    kanji: '九烏亭',
    badge: 'NEW RELEASE',
    badgeType: 'new',
    genre: 'Mystery',
    genres: ['Mystery', 'Psychological Suspense', 'Supernatural'],
    year: '2026',
    rating: '16+',
    match: '94% Match',
    seasonsCount: '1 Season (13 Episodes)',
    trailerVideo: '/kamui-animation.mp4',
    fullVideo: '/kamui-animation.mp4',
    hook: 'Every guest checked in under a false name. Then room seven was found locked from the inside.',
    synopsis: 'Every guest at the Nine Crows arrives already lying about something. The innkeeper doesn\'t mind — until a body turns up in room seven and everyone\'s alibi is the same story, word for word.',
    cast: 'Takehito Koyasu, Yoko Hikasa, Hiroshi Kamiya, Kenjiro Tsuda',
    mood: 'Tense, Atmospheric, Clever Whodunit, Chilling',
    studio: 'Ufotable × Kamui',
    director: 'Haruo Sotozaki',
    audio: 'Japanese [Original], English (Dub), French',
    subtitles: 'English [CC], Japanese, Spanish, German',
    maturityDesc: 'Murder mystery, dark suspense, psychological tension.',
    episodes: [
      { num: 1, title: 'The Sealed Room', duration: '24m', desc: 'Heavy snowfall cuts off the mountain pass just as the bell rings ominously in room seven.' },
      { num: 2, title: 'Nine Alibis', duration: '25m', desc: 'The detective begins interrogations, only to discover every suspect gives the exact same statement.' },
      { num: 3, title: 'Crow in the Rafters', duration: '23m', desc: 'A missing ledger reveals the true identity of the inn\'s mysterious masked patron.' },
      { num: 4, title: 'The Midnight Footsteps', duration: '24m', desc: 'Creaking floorboards outside the east wing hallway reveal an unseen ninth guest.' }
    ],
    relatedIds: ['static-requiem', 'kamui', 'long-thaw']
  },
  'glasshouse': {
    id: 'glasshouse',
    title: 'Glasshouse',
    kanji: '温室',
    badge: 'ROMANCE HIT',
    genre: 'Romance',
    genres: ['Romance', 'Drama', 'Slice of Life'],
    year: '2026',
    rating: '13+',
    match: '93% Match',
    seasonsCount: '1 Season (12 Episodes)',
    trailerVideo: '/kamui-hero.mp4',
    fullVideo: '/kamui-hero.mp4',
    hook: 'Two rival florists who refuse to speak share a single delivery van when disaster strikes.',
    synopsis: 'Two florists share a wall and a delivery van and have never once agreed to speak to each other. Then a citywide frost kills both their shops\' stock on the same morning.',
    cast: 'Reina Ueda, Yuichi Nakamura, Ayane Sakura, Nobunaga Shimazaki',
    mood: 'Bittersweet, Aesthetic, Romantic, Tender',
    studio: 'CloverWorks × Kamui',
    director: 'Shinichiro Ushijima',
    audio: 'Japanese [Original], English (Dub), Italian',
    subtitles: 'English [CC], Japanese, French, Portuguese',
    maturityDesc: 'Emotional themes, romantic relationships.',
    episodes: [
      { num: 1, title: 'Morning Frost', duration: '23m', desc: 'The temperature drops drastically overnight, forcing two competitors to share heating generators.' },
      { num: 2, title: 'Winter Roses', duration: '22m', desc: 'A joint rush order for an elite city gala forces them onto the icy road together.' },
      { num: 3, title: 'Behind the Glass', duration: '24m', desc: 'Late night tending of rare orchids leads to an honest conversation in the greenhouse.' },
      { num: 4, title: 'The Blooming Season', duration: '23m', desc: 'The city garden festival arrives with surprising revelations and newfound feelings.' }
    ],
    relatedIds: ['paper-moon-society', 'hollow-meridian', 'nine-crows-inn']
  },
  'hollow-meridian': {
    id: 'hollow-meridian',
    title: 'Hollow Meridian',
    kanji: '空子午線',
    badge: 'ADVENTURE EPIC',
    genre: 'Adventure',
    genres: ['Adventure', 'Fantasy', 'World Exploration'],
    year: '2026',
    rating: '13+',
    match: '95% Match',
    seasonsCount: '1 Season (24 Episodes)',
    trailerVideo: '/kamui-animation.mp4',
    fullVideo: '/kamui-animation.mp4',
    hook: 'The continent rearranges its geography every full moon. A young cartographer just found the edge.',
    synopsis: 'A cartographer\'s guild has spent three centuries mapping a continent that keeps rearranging itself. The newest apprentice just found a coastline that wasn\'t there yesterday — or maybe wasn\'t there ever.',
    cast: 'Nobuhiko Okamoto, Aoi Yuki, Daisuke Ono, Miyuki Sawashiro',
    mood: 'Sense of Wonder, Grand Journey, Mysterious, Epic',
    studio: 'Wit Studio × Kamui',
    director: 'Tetsuro Araki',
    audio: 'Japanese [Original], English (Dub), German',
    subtitles: 'English [CC], Japanese, Spanish, Russian',
    maturityDesc: 'Fantasy action, exploration peril.',
    episodes: [
      { num: 1, title: 'The Shifting Coast', duration: '25m', desc: 'The guild\'s compass spins wildly as a new mountain range appears overnight.' },
      { num: 2, title: 'Isle of Whispering Wind', duration: '24m', desc: 'Navigating uncharted archipelagos using ancient celestial charts and wind stones.' },
      { num: 3, title: 'The Horizon Gate', duration: '25m', desc: 'A monolithic ruin at the edge of the world responds to the apprentice\'s map.' },
      { num: 4, title: 'Beyond the Meridian', duration: '24m', desc: 'Entering the realm where geography no longer obeys mortal physics.' }
    ],
    relatedIds: ['kamui', 'iron-tide', 'long-thaw']
  },
  'static-requiem': {
    id: 'static-requiem',
    title: 'Static Requiem',
    kanji: '雑音鎮魂歌',
    badge: 'MUST WATCH',
    genre: 'Psychological',
    genres: ['Psychological Thriller', 'Supernatural', 'Mystery'],
    year: '2026',
    rating: '18+',
    match: '96% Match',
    seasonsCount: '1 Season (13 Episodes)',
    trailerVideo: '/kamui-hero.mp4',
    fullVideo: '/kamui-hero.mp4',
    hook: 'A radio frequency that died eleven years ago is broadcasting tonight. And only she can hear the caller.',
    synopsis: 'A radio station that\'s been off the air for eleven years starts broadcasting again, and only one former host can still hear it. Nobody believes her except the show\'s original audience — who never stopped listening.',
    cast: 'Maaya Sakamoto, Kenjiro Tsuda, Romi Park, Akira Ishida',
    mood: 'Unsettling, Mind-Bending, Haunting, Psychological Mystery',
    studio: 'Production I.G × Kamui',
    director: 'Kenji Kamiyama',
    audio: 'Japanese [Original], English (Dub), Spanish',
    subtitles: 'English [CC], Japanese, French, Italian',
    maturityDesc: 'Disturbing psychological themes, horror elements, mild gore.',
    episodes: [
      { num: 1, title: 'Frequency 104.7', duration: '24m', desc: 'Late at night, static on an abandoned broadcasting transmitter begins forming a familiar voice.' },
      { num: 2, title: 'The Midnight Caller', duration: '23m', desc: 'A listener describes events happening in real-time outside the locked recording studio booth.' },
      { num: 3, title: 'Static in the Mirror', duration: '25m', desc: 'Audio waveforms analyzed on the oscilloscope reveal subsonic recordings of a voice long thought dead.' },
      { num: 4, title: 'The Final Broadcast', duration: '26m', desc: 'The transmitter power surges to dangerous levels as the eleven-year-old mystery reaches its climax.' }
    ],
    relatedIds: ['nine-crows-inn', 'ashfall-district', 'kamui']
  },
  'long-thaw': {
    id: 'long-thaw',
    title: 'The Long Thaw',
    kanji: '雪解け',
    badge: 'NEW SEASON',
    badgeType: 'new',
    genre: 'Dark fantasy',
    genres: ['Dark Fantasy', 'Adventure', 'Drama', 'Mythology'],
    year: '2026',
    rating: '16+',
    match: '95% Match',
    seasonsCount: '1 Season (24 Episodes)',
    trailerVideo: '/kamui-animation.mp4',
    fullVideo: '/kamui-animation.mp4',
    hook: 'Set two hundred years after Kamui, a new god has slept through every winter since.',
    synopsis: 'Set two hundred years after the events of Kamui, a new god has slept through every winter since — and this is the season it doesn\'t wake up. A standalone story in the same frostbitten northern realm.',
    cast: 'Satoshi Hino, Saori Hayami, Yuichi Nakamura, Kana Hanazawa',
    mood: 'Mythological, Melancholic, Epic Scale, Visual Splendor',
    studio: 'Kamui Originals × Studio MAPPA',
    director: 'Sunao Katabuchi',
    audio: 'Japanese [Original], English (Dub), French, German',
    subtitles: 'English [CC], Japanese, Spanish, German, French',
    maturityDesc: 'Dark supernatural themes, mild fantasy violence.',
    episodes: [
      { num: 1, title: 'The Sleeper in the Frost', duration: '25m', desc: 'Villagers in the northern pass prepare the annual thaw offering, but the sacred glacier remains unmoving.' },
      { num: 2, title: 'Echoes of the Wolf-God', duration: '24m', desc: 'Ancient petroglyphs in the subterranean ice cavern hint at the first god\'s sacrifice two centuries ago.' },
      { num: 3, title: 'The Thawing Blade', duration: '23m', desc: 'A pilgrimage to the sun shrine uncovers the reason behind the celestial eclipse freezing the land.' },
      { num: 4, title: 'Spring Returns to Oku', duration: '26m', desc: 'Maidens and guardians unite to ignite the eternal hearth fire before the eternal ice claims the empire.' }
    ],
    relatedIds: ['kamui', 'nine-crows-inn', 'hollow-meridian']
  }
};

export const CATALOG_IDS = Object.keys(ANIME_CATALOG);
